env:
  node: true

extends: eslint:recommended

root: true

rules:
  array-bracket-spacing: [0, never, {singleValue: true}]
  brace-style: 0 # TODO: Set to 1|2?
  camelcase: [2, {properties: always}]
  comma-dangle: 0 # TODO: Set to `[2, always|never]`?
  curly: 0 # TODO: Set to 2?
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  indent: [2, 2, {SwitchCase: 1}]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  max-len: [0, 80] # TODO: Set to 1|2?
  new-cap: 2
  no-console: 0 # TODO: Set to 1|2?
  no-mixed-spaces-and-tabs: 2
  no-multi-str: 2
  no-multiple-empty-lines: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-unused-vars: [1, {vars: all, args: none}]
  no-with: 2
  one-var: [2, never]
  operator-linebreak: [2, after]
  quotes: [2, double]
  semi: [2, always]
  space-before-blocks: [2, always]
  space-before-function-paren: 0
  space-in-parens: [2, never]
  space-infix-ops: 2
  space-return-throw-case: 0
  space-unary-ops: 0
